[package]
name = "boss-bot"
version = "0.1.0"
edition = "2021"

[dependencies]
serenity = "0.11.6"
tokio = { version = "1", features = ["full"] }
dotenv = "0.15.0"
openai-rust = "0.5.1"
youtube_dl = "0.9.0"
songbird = "0.3.2"
regex = "1.9.5"
