services:
  boss-bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: spiigot/boss-bot:latest
    container_name: boss-bot-instance
    env_file:
      - .env
    environment:
      DEBIAN_FRONTEND: noninteractive
