# fly.toml app configuration file generated for bossbot on 2024-06-26T16:58:57-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bossbot'
primary_region = 'sjc'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 2
